#!/bin/sh
# -*- sh -*-
# vim: ft=sh

: << =cut

=head1 NAME

litecoind_difficulty - Plugin to monitor the mining difficulty

=head1 CONFIGURATION

 [litecoind*]
    user litecoin

=head1 AUTHOR

Cedric Felizard

=head1 LICENSE

AGPLv3+

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

BINARY=${binary:-"/usr/bin/litecoin-cli"}
DATA_DIR=${data_dir:-"/var/lib/litecoin"}

if [ "$1" = "autoconf" ]; then
    autoconf="yes"

    command -v $BINARY >/dev/null || autoconf="no"

    echo $autoconf
    exit 0
fi

if [ "$1" = "config" ]; then
    echo 'graph_title Difficulty'
    echo 'graph_vlabel difficulty'
    echo 'graph_category litecoind'
    echo 'graph_info This graph shows the mining difficulty.'
    echo 'litecoind_difficulty.label difficulty'
    echo 'litecoind_difficulty.info The current mining difficulty.'
    exit 0
fi

echo "litecoind_difficulty.value $($BINARY -datadir=$DATA_DIR getdifficulty)"

