#!/bin/sh
# -*- sh -*-
# vim: ft=sh

: << =cut

=head1 NAME

litecoind_blockchain_verification - Plugin to monitor the blockchain verification percentage

=head1 CONFIGURATION

 [litecoind*]
    user litecoin
    env.binary litecoin-cli
    env.data_dir /var/lib/litecoin

=head1 AUTHOR

Cedric Felizard

=head1 LICENSE

AGPLv3+

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

BINARY=${binary:-"/usr/bin/litecoin-cli"}
DATA_DIR=${data_dir:-"/var/lib/litecoin"}

if [ "$1" = "autoconf" ]; then
    autoconf="yes"

    command -v $BINARY >/dev/null || autoconf="no"

    echo $autoconf
    exit 0
fi

if [ "$1" = "config" ]; then
    echo 'graph_title Blockchain verification'
    echo 'graph_vlabel percentage'
    echo 'graph_category litecoind'
    echo 'graph_info This graph shows the blockchain verification progress.'
    echo 'litecoind_blockchain_verification.label blockchain verification'
    echo 'litecoind_blockchain_verification.info The current progress of the blockchain verification.'
    exit 0
fi

echo "litecoind_blockchain_verification.value $($BINARY -datadir=$DATA_DIR getblockchaininfo | grep verificationprogress | grep -o '[0-9.]*')"

