---

- name: install prerequisites
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
      - autoconf
      - ca-certificates
      - make
      - gcc
      - g++
      - pkg-config
      - libtool
      - libssl-dev
      - libboost-dev
      - libboost-system-dev
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-thread-dev
      - libevent-dev
      - libdb++-dev
  become: yes

- name: fetch source code
  unarchive:
    src: https://github.com/litecoin-project/litecoin/archive/v{{ litecoin_version }}.tar.gz
    dest: /tmp
    remote_src: True

- name: make clean
  command: make clean
  args:
    chdir: /tmp/litecoin-{{ litecoin_version }}
  ignore_errors: yes

- name: autogen
  command: ./autogen.sh
  args:
    chdir: /tmp/litecoin-{{ litecoin_version }}

- name: configure
  command: >
    ./configure
    --sysconfdir=/etc
    --localstatedir=/var
    --datarootdir=/usr/share
    --disable-shared
    --with-pic
    --disable-upnp-default
    --disable-tests
    --disable-gui-tests
    --disable-bench
    --disable-zmq
    --without-miniupnpc
    --with-utils
    --with-libs
    --with-daemon
    --with-incompatible-bdb
    --with-gui=no
  args:
    chdir: /tmp/litecoin-{{ litecoin_version }}

- name: make
  command: make
  args:
    chdir: /tmp/litecoin-{{ litecoin_version }}

- name: install
  command: make install
  args:
    chdir: /tmp/litecoin-{{ litecoin_version }}
  become: yes
  notify: restart_litecoind
