---

- set_fact:
    litecoin_patch_version_match: ".0"
  when: litecoin_patch_version == ""

- name: get current litecoin version
  command: litecoin-cli -version
  register: litecoin_version_current
  ignore_errors: yes

# - include: compile.yml
#   when: litecoin_version_current.rc != 0 or not litecoin_version_current.stdout is search(litecoin_version_string_match)

# - include: setup.yml

- name: check if munin-node is installed
  command: dpkg -L munin-node
  register: litecoin_munin_node_check
  ignore_errors: yes

- include: munin-plugin.yml
  when: litecoin_munin_node_check.rc == 0
