---

- name: apt install bc
  apt:
    name: bc
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: copy over plugins
  copy:
    src: munin-litecoin/{{ item }}
    dest: /usr/share/munin/plugins/{{ item }}
    mode: 'a+x'
  with_items:
    - litecoind_blockchain_size
    - litecoind_blockchain_verification
    - litecoind_blocks
    - litecoind_connections
    - litecoind_difficulty
    - litecoind_mempool_bytes
    - litecoind_mempool_size
    - litecoind_network_traffic
  become: yes
  notify: litecoin_restart_munin_node

- name: enable unbound_munin_histogram
  file:
    src: /usr/share/munin/plugins/{{ item }}
    dest: /etc/munin/plugins/{{ item }}
    state: link
  with_items:
    - litecoind_blockchain_size
    - litecoind_blockchain_verification
    - litecoind_blocks
    - litecoind_connections
    - litecoind_difficulty
    - litecoind_mempool_bytes
    - litecoind_mempool_size
    - litecoind_network_traffic
  become: yes
  notify: litecoin_restart_munin_node

- name: add munin plugin-conf
  template:
    src: munin-plugin.conf
    dest: /etc/munin/plugin-conf.d/litecoind
    mode: 0644
  become: yes
  notify: litecoin_restart_munin_node
