---

- name: create litecoin user
  user:
    name: "{{ litecoin_user }}"
    shell: /usr/sbin/nologin
    home: "{{ litecoin_home }}"
    system: yes
  become: yes
  when: litecoin_user != 'root'

- name: make sure datadir/home exists
  file:
    path: "{{ litecoin_home }}"
    state: directory
    mode: 0755
  become: yes
  when: litecoin_user == 'root'

- name: check for systemd
  command: systemctl --version
  register: litecoin_systemctl_version
  ignore_errors: yes

- name: add litecoind.service
  template:
    src: litecoind.service.ini
    dest: /lib/systemd/system/litecoind.service
    mode: 0644
  become: yes
  when: litecoin_systemctl_version.rc == 0
  notify:
    - litecoin_reload_systemd
    - restart_litecoind

- name: add litecoind.init
  template:
    src: litecoind.init.sh
    dest: /etc/init.d/litecoind
    mode: "a+x"
  become: yes
  when: litecoin_systemctl_version.rc != 0
  notify: restart_litecoind

- name: create folders
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ litecoin_user }}"
  with_items:
    - "{{ litecoin_conf_pid | dirname }}"
    - /etc/litecoin
  become: yes

- name: add litecoind.conf
  template:
    src: litecoind.conf
    dest: /etc/litecoin/litecoind.conf
    mode: 0640
  become: yes
  become_user: "{{ litecoin_user }}"
  notify: restart_litecoind
