version: 2

jobs:

  build:
    environment:
      MAKEFLAGS: -j 2

    machine: true

    steps:
      - run: pip install ansible
      - run: ansible --version

      - checkout
      - run: printf '[defaults]\nroles_path=../' > ansible.cfg
      - run: ansible-playbook tests/test.yml -i tests/inventory --connection=local
      - run: ansible-playbook tests/test.yml -i tests/inventory --connection=local
      - run: litecoin-cli -version
      - run: sudo cat /etc/litecoin/litecoind.conf
      - run: sudo /etc/init.d/litecoind stop
