---

- name: litecoin_reload_systemd
  command: systemctl daemon-reload
  become: yes

- name: litecoin_restart_munin_node
  service:
    name: munin-node
    state: restarted
  become: yes

- name: restart_litecoind
  service:
    name: litecoind
    state: restarted
    enabled: yes
  become: yes
